# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-07 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intelligentdiagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreehandMeasurementInfo',
            fields=[
                ('freehand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('freehand_studyUID', models.CharField(max_length=255)),
                ('freehand_seriesUID', models.CharField(max_length=255)),
                ('freehand_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('freehand_info', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='IntelligentDiagnosis',
            new_name='IntelligentDiagnosisInfo',
        ),
    ]
